img_size: [128, 128]
batch_size: 10
input_shape: [128, 128, 1]
epochs: 5
model_json_path: "data/07_model_output/model_new.json"
model_weights_path: "data/06_models/model_new.h5"
image_path: "data/04_feature/image.jpg"